
POST http://localhost:2316/bypass
content-type: application/json
authorization: Bearer hello

{
  "url": "https://www.javlibrary.com",
  "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
  "cookies": {
    "hello": "world"
  }
}

###

POST http://167.179.69.228:2316/bypass
content-type: application/json
authorization: Bearer hello

{
  "url": "https://www.javlibrary.com",
  "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
  "cookies": {
    "hello": "world"
  }
}